using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ChessGame
{
    class Program
    {
        static void Main(string[] args)
        {
            Pawn PawnW1 = new Pawn(true, 1);
            PawnW1.SetPosition();
            Console.WriteLine($"- Pawn White 1 X is: {PawnW1.X}");
            Console.WriteLine($"- Pawn White 1 Y is: {PawnW1.Y}");
            Console.WriteLine();
            Pawn PawnW2 = new Pawn(true, 2);
            PawnW2.SetPosition();
            Console.WriteLine($"- Pawn White 2 X is: {PawnW2.X}");
            Console.WriteLine($"- Pawn White 2 Y is: {PawnW2.Y}");
            Console.WriteLine();
            Pawn PawnW3 = new Pawn(true, 3);
            PawnW3.SetPosition();
            Console.WriteLine($"- Pawn White 3 X is: {PawnW3.X}");
            Console.WriteLine($"- Pawn White 3 Y is: {PawnW3.Y}");
            Console.WriteLine();
            Pawn PawnW4 = new Pawn(true, 4);
            PawnW4.SetPosition();
            Console.WriteLine($"- Pawn White 4 X is: {PawnW4.X}");
            Console.WriteLine($"- Pawn White 4 Y is: {PawnW4.Y}");
            Console.WriteLine();
            Pawn PawnW5 = new Pawn(true, 5);
            PawnW5.SetPosition();
            Console.WriteLine($"- Pawn White 5 X is: {PawnW5.X}");
            Console.WriteLine($"- Pawn White 5 Y is: {PawnW5.Y}");
            Console.WriteLine();
            Pawn PawnW6 = new Pawn(true, 6);
            PawnW6.SetPosition();
            Console.WriteLine($"- Pawn White 6 X is: {PawnW6.X}");
            Console.WriteLine($"- Pawn White 6 Y is: {PawnW6.Y}");
            Console.WriteLine();
            Pawn PawnW7 = new Pawn(true, 7);
            PawnW7.SetPosition();
            Console.WriteLine($"- Pawn White 7 X is: {PawnW7.X}");
            Console.WriteLine($"- Pawn White 7 Y is: {PawnW7.Y}");
            Console.WriteLine();
            Pawn PawnW8 = new Pawn(true, 8);
            PawnW8.SetPosition();
            Console.WriteLine($"- Pawn White 8 X is: {PawnW8.X}");
            Console.WriteLine($"- Pawn White 8 Y is: {PawnW8.Y}");
            Console.WriteLine();
            Pawn PawnBl1 = new Pawn(false, 1);
            PawnBl1.SetPosition();
            Console.WriteLine($"- Pawn Black 1 X is: {PawnBl1.X}");
            Console.WriteLine($"- Pawn Black 1 Y is: {PawnBl1.Y}");
            Console.WriteLine();
            Pawn PawnBl2 = new Pawn(false, 2);
            PawnBl2.SetPosition();
            Console.WriteLine($"- Pawn Black 2 X is: {PawnBl2.X}");
            Console.WriteLine($"- Pawn Black 2 Y is: {PawnBl2.Y}");
            Console.WriteLine();
            Pawn PawnBl3 = new Pawn(false, 3);
            PawnBl3.SetPosition();
            Console.WriteLine($"- Pawn Black 3 X is: {PawnBl3.X}");
            Console.WriteLine($"- Pawn Black 3 Y is: {PawnBl3.Y}");
            Console.WriteLine();
            Pawn PawnBl4 = new Pawn(false, 4);
            PawnBl4.SetPosition();
            Console.WriteLine($"- Pawn Black 4 X is: {PawnBl4.X}");
            Console.WriteLine($"- Pawn Black 4 Y is: {PawnBl4.Y}");
            Console.WriteLine();
            Pawn PawnBl5 = new Pawn(false, 5);
            PawnBl5.SetPosition();
            Console.WriteLine($"- Pawn Black 5 X is: {PawnBl5.X}");
            Console.WriteLine($"- Pawn Black 5 Y is: {PawnBl5.Y}");
            Console.WriteLine();
            Pawn PawnBl6 = new Pawn(false, 6);
            PawnBl6.SetPosition();
            Console.WriteLine($"- Pawn Black 6 X is: {PawnBl6.X}");
            Console.WriteLine($"- Pawn Black 6 Y is: {PawnBl6.Y}");
            Console.WriteLine();
            Pawn PawnBl7 = new Pawn(false, 7);
            PawnBl7.SetPosition();
            Console.WriteLine($"- Pawn Black 7 X is: {PawnBl7.X}");
            Console.WriteLine($"- Pawn Black 7 Y is: {PawnBl7.Y}");
            Console.WriteLine();
            Pawn PawnBl8 = new Pawn(false, 8);
            PawnBl8.SetPosition();
            Console.WriteLine($"- Pawn Black 8 X is: {PawnBl8.X}");
            Console.WriteLine($"- Pawn Black 8 Y is: {PawnBl8.Y}");
            Console.WriteLine();
            Rook RookW1 = new Rook(true, 1);
            RookW1.SetPosition();
            Console.WriteLine($"- Rook White Left X is: {RookW1.X}");
            Console.WriteLine($"- Rook White Left Y is: {RookW1.Y}");
            Console.WriteLine();
            Rook RookW2 = new Rook(true, 2);
            RookW2.SetPosition();
            Console.WriteLine($"- Rook White Right X is: {RookW2.X}");
            Console.WriteLine($"- Rook White Right Y is: {RookW2.Y}");
            Console.WriteLine();
            Rook RookBl1 = new Rook(false, 1);
            RookBl1.SetPosition();
            Console.WriteLine($"- Rook Black Left X is: {RookBl1.X}");
            Console.WriteLine($"- Rook Black Left Y is: {RookBl1.Y}");
            Console.WriteLine();
            Rook RookBl2 = new Rook(false, 2);
            RookBl2.SetPosition();
            Console.WriteLine($"- Rook Black Right X is: {RookBl2.X}");
            Console.WriteLine($"- Rook Black Right Y is: {RookBl2.Y}");
            Console.WriteLine();
            Knight KnightW1 = new Knight(true, 1);
            KnightW1.SetPosition();
            Console.WriteLine($"- Knight White Left X is: {KnightW1.X}");
            Console.WriteLine($"- Knight White Left Y is: {KnightW1.Y}");
            Console.WriteLine();
            Knight KnightW2 = new Knight(true, 2);
            KnightW2.SetPosition();
            Console.WriteLine($"- Knight White Right X is: {KnightW2.X}");
            Console.WriteLine($"- Knight White Right Y is: {KnightW2.Y}");
            Console.WriteLine();
            Knight KnightBl1 = new Knight(false, 1);
            KnightBl1.SetPosition();
            Console.WriteLine($"- Knight Black Left X is: {KnightBl1.X}");
            Console.WriteLine($"- Knight Black Left Y is: {KnightBl1.Y}");
            Console.WriteLine();
            Knight KnightBl2 = new Knight(false, 2);
            KnightBl2.SetPosition();
            Console.WriteLine($"- Knight Black Right X is: {KnightBl2.X}");
            Console.WriteLine($"- Knight Black Right Y is: {KnightBl2.Y}");
            Console.WriteLine();
            Bishop BishopW1 = new Bishop(true, 1);
            BishopW1.SetPosition();
            Console.WriteLine($"- Bishop White Left X is: {BishopW1.X}");
            Console.WriteLine($"- Bishop White Left Y is: {BishopW1.Y}");
            Console.WriteLine();
            Bishop BishopW2 = new Bishop(true, 2);
            BishopW2.SetPosition();
            Console.WriteLine($"- Bishop White Right X is: {BishopW2.X}");
            Console.WriteLine($"- Bishop White Right Y is: {BishopW2.Y}");
            Console.WriteLine();
            Bishop BishopBl1 = new Bishop(false, 1);
            BishopBl1.SetPosition();
            Console.WriteLine($"- Bishop Black Left X is: {BishopBl1.X}");
            Console.WriteLine($"- Bishop Black Left Y is: {BishopBl1.Y}");
            Console.WriteLine();
            Bishop BishopBl2 = new Bishop(false, 2);
            BishopBl2.SetPosition();
            Console.WriteLine($"- Bishop Black Right X is: {BishopBl2.X}");
            Console.WriteLine($"- Bishop Black Right Y is: {BishopBl2.Y}");
            Console.WriteLine();
            Queen QueenW = new Queen(true);
            QueenW.SetPosition();
            Console.WriteLine($"- Queen White X is: {QueenW.X}");
            Console.WriteLine($"- Queen White Y is: {QueenW.Y}");
            Console.WriteLine();
            Queen QueenBl = new Queen(false);
            QueenBl.SetPosition();
            Console.WriteLine($"- Queen Black X is: {QueenBl.X}");
            Console.WriteLine($"- Queen Black Y is: {QueenBl.Y}");
            Console.WriteLine();
            King KingW = new King(true);
            KingW.SetPosition();
            Console.WriteLine($"- King White X is: {KingW.X}");
            Console.WriteLine($"- King White Y is: {KingW.Y}");
            Console.WriteLine();
            King KingBl = new King(false);
            KingBl.SetPosition();
            Console.WriteLine($"- King Black X is: {KingBl.X}");
            Console.WriteLine($"- King Black Y is: {KingBl.Y}");
            Console.WriteLine();
        }
    }
}
